clc;
%% LOAD DATA OF SCHOOL%%
%% wattage (w)|qty (nos|average use time (h/day)%%%
loaddata_scl=[11 16 4
    9 4 8
    9 1 8
    9 1 8
    11 3 8
    200 7 8
    360 1 8
    35 8 4
    30 4 8
    3 4 4];

%% LOAD DATA OF 1 HOUSE%%
%% wattage (w)|qty (nos|average use time (h/day)%%%
loaddata_hm=[2 5 4
    1 7 4
    25 1 14
    3 1 2];

temp1=size(loaddata_scl); %temp is a temporary variable
temp2=size(loaddata_hm);
%size(A) returns a two-element row vector consisting 
% of the number of rows and the number of table variables.

nld_scl=temp1(1,1);
nld_hm=temp2(1,1);
%%%nld = number of loads%%%

 %%%% daily energy consumption in wh for 24 Hours%%%%
E1=0;

for i=1:1:nld_scl
    E1=E1+loaddata_scl(i,1)*loaddata_scl(i,2)*loaddata_scl(i,3);
end

E2=0;

for j=1:1:nld_hm
    E2=E2+loaddata_hm(j,1)*loaddata_hm(j,2)*loaddata_hm(j,3);
end

E= (E1+E2*90)*1.1;  %Calculations are for 10% more energy

PVsizeint=250; %%% peak wattage %%%
EPV=PVsizeint*24*0.15; %%%% ENERGY GENERATED BY 250 W PANEL IN 24 HOURS %%%
%here %age efficiency is 15%

PVsize=(E/EPV)*PVsizeint;%PV panel size / power generated in wp
npv=floor(E/EPV)+1;%npv is number of pv panels
%%%npv = number of pv panels%%%

%Solar panels are 
%approximately 2 m2 with roughly one additional m2 for inter-row spacing
%SOURCE: IEEE STANDARDS BOOKLET THAT WAS PROVIDED
Area_covered=3*npv;

%To calculate the battery energy storage capacity needed. A simplifying assumption can be made to 
%assume that all the microgrid energy is consumed at night. Formula used
%is:

%Ebatt= (h*v*d*I)/D*V wh (given in IEEE standards)

%which is equivalent to: Ebatt= (E*d)/D in watt hours

%h=hours usage
%v=Voltage 48V
%d=days without sun
%I=total current
%D=depth of discharge
%V= 48V System voltage
%E=Net Energy consumption

D=0.8; %depth of discharge is taken 80%
d=3; %number of days without sun
Ebatt = (E*3)/(D*48); 
Ebatt_req = Ebatt*1.2; %Considering 20% extra battery capacity than required

%% (DC TO DC CONVERTER RATING)%%%
%Most PV panel manufacturers produce standard solar panels with output voltage of 12 volt and 24 volts.
%So we will take 12 volt here as the output voltage of the panel and this
%would be the dc converter input voltage.

%SOURCE:https://www.alternative-energy-tutorials.com/photovoltaics/photovoltaic-panel.html
%We need the output voltage from the converter as 48V.

%INPUT VOLTAGE=12V AND OUTPUT VOLTAGE =48V

%SOLAR IRRADIATION DATA HAS BEEN TAKEN FROM IEEE STANDARDS
%required PV capacity can be calculated using a solar calculator
%National Renewable Energy Lab (NREL) PVWatts® Calculator
%available at https://pvwatts.nrel.gov/.

%ENTER "VARANASI" IN ADDRESS COLUMN
%Latitude displayed=25.33° N , Longitude displayed=83.02° E
%IN RESULTS SECTION For this example, the 
%calculator shows that August is the least productive month
Monthly_Usage=(E*30)/1000;  %in kwh
%Monthly production of AUGUST = 425 kwh


P1=0;  %POWER OF SCHOOL
for i=1:1:nld_scl
    P1=P1+loaddata_scl(i,1)*loaddata_scl(i,2);
end

P2=0;  %POWER OF HOUSES
for j=1:1:nld_hm
    P2=P2+loaddata_hm(j,1)*loaddata_hm(j,2);
end
P2=P2*30;
P=P1+P2;%Net power of branch containing school and 30 houses

%current requirement of the branch containing school and houses has been
%taken in consideration so as to choose the conductor which would allow the
%flow of maximum required current
I= P/48; %As standard system voltage for DC is 48V so I=P/V
Vd=5; %Budgeted Voltage Drop
R_branch= Vd/I; %maximum resistance per segment (THIS FORMULA IS GIVEN IN IEEE STANDARDS)
%considering the branch (i.e. the microgrid segment) containing the school for calculation of
%resistance per metre of the cable
Dist=(30*12)+20; %30 homes in a branch seprated by 12m and 20 m is the
%distance of school
R_km= (R_branch*1000)/Dist; %Maximum Resistance per km

%CABLE DATA
%%CABLE SIZING ON THE LOAD SIDE OF DC BUS taken from
%https://www.smsystems.co.in/POLYCAB-SOLAR-Cable.pdf

%% SINGLE CORE SIZE(Sq.mm)|Maximum Resistance (ohms/km)|CURRENT CARRYING CAPACITY OF DC SOLAR CABLE(in amps)%%
cable_data = [1.5 13.3 25 
2.5 7.98 35 
4 4.95 45 
6 3.30 58 
10 1.910 80 
16 1.210 106 
25 0.780 135 
35 0.554 173 
50 0.386 226 
70 0.272 336 
95 0.206 406 
120 0.161 476 
150 0.129 555 
185 0.106 649 
240 0.0801 781];

%Select the required wire gauge by calculating the maximum resistance per km and then using the 
%above table of resistance for the type of wire that will be used and selecting the smallest diameter wire 
%whose resistance per meter is less than the calculated maximum (GIVEN IN
%IEEE STANDARDS B.3)
temp3=size(cable_data);
nc=temp3(1,1);  %nc=number of cables to choose from
for c=1:1:nc
     if c==1 && R_km > cable_data(c,2)
        %% SPECIFICATIONS OF THE CABLE CHOSEN%%
       R_req= cable_data(c,2);
       CORE_SIZE=cable_data(c,1);
       Current_cap=cable_data(c,3);
     elseif c > 1 && cable_data(c-1,2)> R_km && R_km> cable_data(c,2)
        %% SPECIFICATIONS OF THE CABLE CHOSEN%%
       R_req= cable_data(c,2);
       CORE_SIZE=cable_data(c,1);
       Current_cap=cable_data(c,3);
   
    end  
end



%************************************************************************
%CODE OUTPUT / CONCLUSION

%PV PANEL SIZE = 17.040 kwp
%DC/DC CONVERTER RATING (BOOST CONVERTER) = 12 TO 48
%BATTERY SIZE = 5.7511 * 10^3 ampere hour
%CABLE SPECIFICATIONS:
% Resistance = 0.161 ohms/km
%Core size = 120 sq mm
%Current Carrying Capacity = 476 amps


